version: '3.1'

services:
  db:
    image: mongo
    restart: on-failure
    volumes:
      - db-data:/etc/mongo
  client:
    build: ./mern/client
    depends_on:
      - server
      - ai
    ports:
      - "3001:3001"
  server:
    build: ./mern/server
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - ATLAS_URI=mongodb://db:27017
  ai:
    build: ./AI
    ports:
      - "8000:8000"

volumes:
  db-data: